# Generated by Django 5.0.4 on 2024-06-26 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, max_length=700, null=True, verbose_name='Ссылка'),
        ),
    ]
