# Generated by Django 5.0.4 on 2024-09-12 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_mainpagearticle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpagearticle',
            name='header',
            field=models.CharField(max_length=750, verbose_name='Название'),
        ),
    ]
