# Generated by Django 5.0.4 on 2024-10-09 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_mainpagearticle_header'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=750, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Раздел документации',
                'verbose_name_plural': 'Разделы документации',
            },
        ),
        migrations.CreateModel(
            name='Documentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=750, verbose_name='Название')),
                ('file', models.FileField(upload_to='documentation/', verbose_name='Файл')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('doc_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.docsection')),
            ],
            options={
                'verbose_name': 'Документация',
                'verbose_name_plural': 'Документация',
            },
        ),
    ]
