# Generated by Django 5.0.4 on 2024-10-09 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_docsection_documentation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentation',
            name='doc_section',
        ),
        migrations.DeleteModel(
            name='DocSection',
        ),
    ]
