# Generated by Django 5.0.4 on 2024-10-09 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_documentation_doc_section_delete_docsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentation',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
    ]
