# Generated by Django 5.0.4 on 2024-06-15 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0008_schoolcloster_remove_school_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('closter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='schools.schoolcloster', verbose_name='Кластер')),
            ],
            options={
                'verbose_name': 'Отчёт (шаблон)',
                'verbose_name_plural': 'Отчёты (шаблоны)',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер раздела')),
                ('name', models.CharField(max_length=250, verbose_name='Название раздела')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='reports.report', verbose_name='отчёт')),
            ],
            options={
                'verbose_name': 'Раздел отчёта',
                'verbose_name_plural': 'Разделы отчётов',
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер поля')),
                ('name', models.CharField(max_length=250, verbose_name='Название раздела')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='reports.section', verbose_name='раздел')),
            ],
            options={
                'verbose_name': 'Поле отчёта',
                'verbose_name_plural': 'Поля отчётов',
            },
        ),
    ]
