# Generated by Django 5.0.4 on 2024-06-16 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_option_delete_criterion_alter_field_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='field',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='reports.field', verbose_name='показатель'),
            preserve_default=False,
        ),
    ]
