# Generated by Django 5.0.4 on 2024-06-16 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_option_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer_type',
            field=models.CharField(choices=[('BL', 'Бинарный выбор (Да/Нет)'), ('LST', 'Выбор из списка'), ('NMBR', 'Числовое значение'), ('PRC', 'Процент')], max_length=5, verbose_name='Тип ответа'),
        ),
        migrations.CreateModel(
            name='RangeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range_type', models.CharField(choices=[('L', 'Меньше или равно'), ('G', 'Больше или равно'), ('D', 'Диапазон')], max_length=1, verbose_name='Тип условия')),
                ('less_or_equal', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True, verbose_name='Меьньше или равно')),
                ('greater_or_equal', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True, verbose_name='Больше или равно')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='range_options', to='reports.question', verbose_name='критерий')),
            ],
            options={
                'verbose_name': 'Диапозон',
                'verbose_name_plural': 'Диапазоны',
            },
        ),
    ]
