# Generated by Django 5.0.4 on 2024-06-16 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_alter_question_answer_type_rangeoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='number',
            field=models.CharField(max_length=500, verbose_name='Номер раздела'),
        ),
    ]
