# Generated by Django 5.0.4 on 2024-06-16 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_alter_section_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='number',
            field=models.CharField(max_length=500, verbose_name='Номер поля'),
        ),
    ]
