# Generated by Django 5.0.4 on 2024-06-17 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_alter_field_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='points',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Колво баллов'),
        ),
        migrations.AlterField(
            model_name='rangeoption',
            name='greater_or_equal',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=5, null=True, verbose_name='Больше или равно'),
        ),
        migrations.AlterField(
            model_name='rangeoption',
            name='less_or_equal',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=5, null=True, verbose_name='Меьньше или равно'),
        ),
    ]
