# Generated by Django 5.0.4 on 2024-06-17 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_alter_question_bool_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='name',
            field=models.CharField(default='тест', max_length=750, verbose_name='Название отчёта'),
            preserve_default=False,
        ),
    ]
