# Generated by Django 5.0.4 on 2024-06-17 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_answer_schoolreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='s_report',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='reports.schoolreport', verbose_name='отчёт'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schoolreport',
            name='status',
            field=models.CharField(choices=[('I', 'Создан'), ('G', 'Заполнение'), ('D', 'На согласовании в ТУ/ДО'), ('D', 'На согласовании в МинОбр'), ('D', 'Принят')], default='I', max_length=1, verbose_name='Тип условия'),
            preserve_default=False,
        ),
    ]
