# Generated by Django 5.0.4 on 2024-06-17 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_answer_s_report_schoolreport_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='reports.section', verbose_name='раздел'),
        ),
    ]
