# Generated by Django 5.0.4 on 2024-06-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_alter_field_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolreport',
            name='status',
            field=models.CharField(choices=[('C', 'Заполнение'), ('A', 'На согласовании в ТУ/ДО'), ('B', 'На согласовании в МинОбр'), ('D', 'Принят')], default='C', max_length=1, verbose_name='Тип условия'),
        ),
    ]
