# Generated by Django 5.0.4 on 2024-06-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_alter_schoolreport_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='rangeoption',
            name='equal',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=5, null=True, verbose_name='Равно'),
        ),
        migrations.AlterField(
            model_name='rangeoption',
            name='range_type',
            field=models.CharField(choices=[('L', 'Меньше или равно'), ('G', 'Больше или равно'), ('D', 'Диапазон'), ('E', 'Равно')], max_length=1, verbose_name='Тип условия'),
        ),
        migrations.AlterField(
            model_name='schoolreport',
            name='status',
            field=models.CharField(choices=[('C', 'Заполнение'), ('A', 'На согласовании в ТУ/ДО'), ('B', 'На согласовании в МинОбр'), ('D', 'Принят')], default='C', max_length=1, verbose_name='Статус'),
        ),
    ]
