# Generated by Django 5.0.4 on 2024-06-18 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0015_rangeoption_equal_alter_rangeoption_range_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='number',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Номер раздела'),
        ),
    ]
