# Generated by Django 5.0.4 on 2024-06-18 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0016_alter_section_number'),
        ('schools', '0009_rename_сloster_school_closter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='closter',
        ),
        migrations.CreateModel(
            name='ReportZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(choices=[('R', 'Красная'), ('Y', 'Желтая'), ('G', 'Зеленая')], max_length=5, verbose_name='Зона')),
                ('school_type', models.CharField(choices=[('A', '1 — 11 классы'), ('M', '1 — 9 классы'), ('S', '1 — 4 классы'), ('G', '10 — 11 классы'), ('MG', '5 — 11 классы')], max_length=2, verbose_name='Тип школы')),
                ('closter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='schools.schoolcloster', verbose_name='Кластер')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='reports.report', verbose_name='отчёт')),
            ],
            options={
                'verbose_name': 'Отчёт (шаблон)',
                'verbose_name_plural': 'Отчёты (шаблоны)',
            },
        ),
    ]
