# Generated by Django 5.0.4 on 2024-06-18 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0017_remove_report_closter_reportzone'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportzone',
            name='greater_or_equal',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=5, null=True, verbose_name='Больше или равно'),
        ),
        migrations.AddField(
            model_name='reportzone',
            name='less_or_equal',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=5, null=True, verbose_name='Меьньше или равно'),
        ),
        migrations.AddField(
            model_name='reportzone',
            name='range_type',
            field=models.CharField(choices=[('L', 'Меньше или равно'), ('G', 'Больше или равно'), ('D', 'Диапазон')], default=1, max_length=1, verbose_name='Тип условия'),
            preserve_default=False,
        ),
    ]
