# Generated by Django 5.0.4 on 2024-06-18 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0018_reportzone_greater_or_equal_reportzone_less_or_equal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportzone',
            name='greater_or_equal',
        ),
        migrations.RemoveField(
            model_name='reportzone',
            name='less_or_equal',
        ),
        migrations.AddField(
            model_name='reportzone',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=5, null=True, verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='reportzone',
            name='range_type',
            field=models.CharField(choices=[('L', 'Меньше или равно'), ('G', 'Больше или равно')], max_length=1, verbose_name='Тип условия'),
        ),
    ]
