# Generated by Django 5.0.4 on 2024-06-18 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0020_remove_reportzone_value_reportzone_greater_or_equal_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportzone',
            options={'verbose_name': 'Зона', 'verbose_name_plural': 'Зоны'},
        ),
    ]
