# Generated by Django 5.0.4 on 2024-06-23 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0022_remove_reportzone_school_type_reportzone_ed_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='reports.option', verbose_name='опция'),
        ),
    ]
