# Generated by Django 5.0.4 on 2024-06-23 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0023_alter_answer_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='bool_value',
            field=models.BooleanField(default=None, null=True, verbose_name='Бинарный выбор'),
        ),
        migrations.AddField(
            model_name='answer',
            name='points',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Колво баллов'),
        ),
    ]
