# Generated by Django 5.0.4 on 2024-06-23 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0024_answer_bool_value_answer_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='rangeoption',
            name='points',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Колво баллов'),
        ),
    ]
