# Generated by Django 5.0.4 on 2024-06-24 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0026_answer_number_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='bool_value',
            field=models.BooleanField(default=False, null=True, verbose_name='Бинарный выбор'),
        ),
    ]
