# Generated by Django 5.0.4 on 2024-06-25 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0027_alter_answer_bool_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_ready',
            field=models.BooleanField(default=False, verbose_name='Готов к отправке?'),
        ),
    ]
