# Generated by Django 5.0.4 on 2024-06-25 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0028_answer_is_ready'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='is_ready',
        ),
        migrations.AddField(
            model_name='schoolreport',
            name='is_ready',
            field=models.BooleanField(default=False, verbose_name='Готов к отправке?'),
        ),
    ]
