# Generated by Django 5.0.4 on 2024-06-25 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0029_remove_answer_is_ready_schoolreport_is_ready'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Опубликовать?'),
        ),
    ]
