# Generated by Django 4.2.6 on 2024-07-10 08:44

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0030_report_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='note',
            field=tinymce.models.HTMLField(blank=True, default=None, null=True, verbose_name='Примечание'),
        ),
        migrations.AddField(
            model_name='question',
            name='note',
            field=tinymce.models.HTMLField(blank=True, default=None, null=True, verbose_name='Примечание'),
        ),
    ]
