# Generated by Django 4.2.6 on 2024-07-10 09:06

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0031_field_note_question_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='note',
            field=tinymce.models.HTMLField(blank=True, default=None, null=True, verbose_name='Примечание'),
        ),
    ]
