# Generated by Django 4.2.6 on 2024-07-10 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0033_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='report',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='reports.report', verbose_name='отчёт'),
            preserve_default=False,
        ),
    ]
