# Generated by Django 4.2.6 on 2024-07-11 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0035_alter_report_options_attachment_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='file',
        ),
        migrations.CreateModel(
            name='ReportFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, max_length=200, null=True, upload_to='media/attachments/', verbose_name='Файл')),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='reports.attachment', verbose_name='вложение (отчёт)')),
                ('s_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='reports.schoolreport', verbose_name='отчёт')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
            },
        ),
    ]
