# Generated by Django 4.2.6 on 2024-07-11 08:24

from django.db import migrations, models
import reports.models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0036_remove_attachment_file_reportfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportfile',
            name='file',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to=reports.models.ReportFile.file_path, verbose_name='Файл'),
        ),
    ]
