# Generated by Django 4.2.6 on 2024-07-15 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0037_alter_reportfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_mod_by_ter',
            field=models.BooleanField(default=False, verbose_name='Изменён ТУ/ДО?'),
        ),
    ]
