# Generated by Django 4.2.6 on 2024-07-28 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0038_answer_is_mod_by_ter'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolreport',
            name='points',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Колво баллов'),
        ),
        migrations.AddField(
            model_name='schoolreport',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='s_reports', to='reports.reportzone', verbose_name='Зона'),
        ),
    ]
