# Generated by Django 4.2.6 on 2024-07-28 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0039_schoolreport_points_schoolreport_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='points',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Макс. баллов'),
        ),
    ]
