# Generated by Django 4.2.6 on 2024-08-31 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0012_school_ed_level_alter_school_school_type'),
        ('reports', '0041_answer_is_mod_by_mo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='field',
            options={'verbose_name': 'Критерий', 'verbose_name_plural': 'Критерии'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Условие', 'verbose_name_plural': 'Условия'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'Показатель отчёта', 'verbose_name_plural': 'Показатели отчётов'},
        ),
        migrations.AddField(
            model_name='report',
            name='closter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='schools.schoolcloster', verbose_name='Кластер'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='ed_level',
            field=models.CharField(choices=[('A', '1 — 11 классы'), ('M', '1 — 9 классы'), ('S', '1 — 4 классы'), ('G', '10 — 11 классы'), ('MG', '5 — 11 классы')], default=1, max_length=2, verbose_name='Уровень образования'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='green_zone_min',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=5, null=True, verbose_name='Зеленая зона (минимум)'),
        ),
        migrations.AddField(
            model_name='report',
            name='yellow_zone_min',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=5, null=True, verbose_name='Жёлтая зона (минимум)'),
        ),
    ]
