# Generated by Django 4.2.6 on 2024-08-31 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0042_alter_field_options_alter_question_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='green_zone_min',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=5, null=True, verbose_name='Зеленая зона (минимум)'),
        ),
        migrations.AddField(
            model_name='section',
            name='yellow_zone_min',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=5, null=True, verbose_name='Жёлтая зона (минимум)'),
        ),
        migrations.RemoveField(
            model_name='section',
            name='report',
        ),
        migrations.AddField(
            model_name='section',
            name='report',
            field=models.ManyToManyField(related_name='sections', to='reports.report', verbose_name='отчёт'),
        ),
    ]
