# Generated by Django 4.2.6 on 2024-08-31 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0043_section_green_zone_min_section_yellow_zone_min_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='report',
            new_name='reports',
        ),
    ]
