# Generated by Django 4.2.6 on 2024-08-31 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0045_alter_section_reports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='reports',
            field=models.ManyToManyField(related_name='sections', to='reports.report', verbose_name='отчёт'),
        ),
    ]
