# Generated by Django 4.2.6 on 2024-08-31 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0046_alter_section_reports'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='reports',
        ),
        migrations.AddField(
            model_name='report',
            name='reports',
            field=models.ManyToManyField(related_name='reports', to='reports.section', verbose_name='показатели'),
        ),
    ]
