# Generated by Django 4.2.6 on 2024-08-31 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0047_remove_section_reports_report_reports'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='reports',
            new_name='sections',
        ),
    ]
