# Generated by Django 4.2.6 on 2024-08-31 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0048_rename_reports_report_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='green_zone_min',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=5, null=True, verbose_name='Зеленая зона (минимум)'),
        ),
        migrations.AddField(
            model_name='field',
            name='points',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Макс. баллов'),
        ),
        migrations.AddField(
            model_name='field',
            name='yellow_zone_min',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=5, null=True, verbose_name='Жёлтая зона (минимум)'),
        ),
        migrations.AddField(
            model_name='option',
            name='zone',
            field=models.CharField(choices=[('R', 'Красная'), ('Y', 'Желтая'), ('G', 'Зеленая')], default=1, max_length=5, verbose_name='Зона'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='points',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Макс. баллов'),
        ),
    ]
