# Generated by Django 5.0.4 on 2024-09-11 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0049_field_green_zone_min_field_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='green_zone_min',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=5, null=True, verbose_name='Зеленая зона (минимум)'),
        ),
        migrations.AddField(
            model_name='option',
            name='yellow_zone_min',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=5, null=True, verbose_name='Жёлтая зона (минимум)'),
        ),
        migrations.AddField(
            model_name='question',
            name='green_zone_min',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=5, null=True, verbose_name='Зеленая зона (минимум)'),
        ),
        migrations.AddField(
            model_name='question',
            name='yellow_zone_min',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=5, null=True, verbose_name='Жёлтая зона (минимум)'),
        ),
        migrations.AddField(
            model_name='rangeoption',
            name='green_zone_min',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=5, null=True, verbose_name='Зеленая зона (минимум)'),
        ),
        migrations.AddField(
            model_name='rangeoption',
            name='yellow_zone_min',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=5, null=True, verbose_name='Жёлтая зона (минимум)'),
        ),
        migrations.AlterField(
            model_name='field',
            name='name',
            field=models.CharField(max_length=750, verbose_name='Название критерия'),
        ),
        migrations.AlterField(
            model_name='field',
            name='number',
            field=models.CharField(max_length=500, verbose_name='Номер критерия'),
        ),
        migrations.AlterField(
            model_name='field',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='reports.section', verbose_name='показатель'),
        ),
        migrations.AlterField(
            model_name='question',
            name='name',
            field=models.CharField(blank=True, max_length=750, null=True, verbose_name='Описание условия'),
        ),
    ]
