# Generated by Django 5.0.4 on 2024-09-11 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0050_option_green_zone_min_option_yellow_zone_min_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='green_zone_min',
        ),
        migrations.RemoveField(
            model_name='question',
            name='yellow_zone_min',
        ),
        migrations.AddField(
            model_name='rangeoption',
            name='zone',
            field=models.CharField(choices=[('R', 'Красная'), ('Y', 'Желтая'), ('G', 'Зеленая')], default=1, max_length=5, verbose_name='Зона'),
            preserve_default=False,
        ),
    ]
