# Generated by Django 5.0.4 on 2024-09-12 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0053_alter_field_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='field',
            options={'get_latest_by': ['-id'], 'verbose_name': 'Критерий', 'verbose_name_plural': 'Критерии'},
        ),
    ]
