# Generated by Django 5.0.4 on 2024-09-12 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0054_alter_field_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='zone',
            field=models.CharField(choices=[('R', 'Красная'), ('Y', 'Желтая'), ('G', 'Зеленая')], default='Y', max_length=5, verbose_name='Зона'),
            preserve_default=False,
        ),
    ]
