# Generated by Django 5.0.4 on 2024-09-12 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0055_answer_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolreport',
            name='zone',
            field=models.CharField(choices=[('R', 'Красная'), ('Y', 'Желтая'), ('G', 'Зеленая')], default='R', max_length=5, verbose_name='Зона'),
            preserve_default=False,
        ),
    ]
