# Generated by Django 5.0.4 on 2024-09-12 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0057_question_attachment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'verbose_name': 'Источник данных', 'verbose_name_plural': 'Источники данных'},
        ),
        migrations.AlterField(
            model_name='attachment',
            name='attachment_type',
            field=models.CharField(blank=True, choices=[('DC', 'Документ (прикреплённый файл)'), ('LNK', 'Ссылка'), ('OTH', 'Иной источник (без ссылки/файла)')], max_length=3, null=True, verbose_name='Цель обучения'),
        ),
    ]
