# Generated by Django 5.0.4 on 2024-09-12 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0058_alter_attachment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rangeoption',
            name='range_type',
            field=models.CharField(choices=[('L', 'Меньше или равно'), ('G', 'Больше или равно'), ('D', 'Диапазон'), ('E', 'Равно')], default='D', max_length=1, verbose_name='Тип условия'),
        ),
    ]
