# Generated by Django 5.0.4 on 2024-09-22 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0059_alter_rangeoption_range_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='section',
        ),
        migrations.RemoveField(
            model_name='report',
            name='sections',
        ),
        migrations.AddField(
            model_name='field',
            name='sections',
            field=models.ManyToManyField(blank=True, related_name='fields', to='reports.section', verbose_name='Показатели'),
        ),
        migrations.AddField(
            model_name='section',
            name='report',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='reports.report', verbose_name='отчёт'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ReportZone',
        ),
    ]
