# Generated by Django 5.0.4 on 2024-09-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0060_remove_field_section_remove_report_sections_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='sections',
        ),
        migrations.AddField(
            model_name='section',
            name='fields',
            field=models.ManyToManyField(blank=True, related_name='sections', to='reports.field', verbose_name='Критерии'),
        ),
    ]
