# Generated by Django 5.0.4 on 2024-09-22 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0061_remove_field_sections_section_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='field',
            new_name='report_field',
        ),
    ]
