# Generated by Django 5.0.4 on 2024-09-24 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0064_report_is_counting_alter_rangeoption_less_or_equal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='green_zone_min',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Зеленая зона (минимум)'),
        ),
        migrations.AlterField(
            model_name='field',
            name='yellow_zone_min',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Жёлтая зона (минимум)'),
        ),
        migrations.AlterField(
            model_name='section',
            name='green_zone_min',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Зеленая зона (минимум)'),
        ),
        migrations.AlterField(
            model_name='section',
            name='yellow_zone_min',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Жёлтая зона (минимум)'),
        ),
    ]
