# Generated by Django 5.0.4 on 2024-09-24 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0065_alter_field_green_zone_min_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='report',
        ),
    ]
