# Generated by Django 5.0.4 on 2024-09-24 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0066_remove_attachment_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportfile',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='reports.question', verbose_name='условие'),
            preserve_default=False,
        ),
    ]
