# Generated by Django 5.0.4 on 2024-09-24 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0067_reportfile_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportfile',
            name='question',
        ),
    ]
