# Generated by Django 5.0.4 on 2024-09-24 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0068_remove_reportfile_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportfile',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='files', to='reports.question', verbose_name='условие'),
        ),
    ]
