# Generated by Django 5.0.4 on 2024-09-24 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0069_reportfile_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportfile',
            name='questions',
        ),
        migrations.AddField(
            model_name='reportfile',
            name='answers',
            field=models.ManyToManyField(blank=True, related_name='files', to='reports.answer', verbose_name='условие'),
        ),
    ]
