# Generated by Django 5.0.4 on 2024-09-24 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0070_remove_reportfile_questions_reportfile_answers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['-id'], 'verbose_name': 'Показатель отчёта', 'verbose_name_plural': 'Показатели отчётов'},
        ),
    ]
