# Generated by Django 5.0.4 on 2024-09-25 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0071_alter_section_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'Показатель отчёта', 'verbose_name_plural': 'Показатели отчётов'},
        ),
    ]
