# Generated by Django 5.0.4 on 2024-09-25 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0071_alter_section_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='zone',
            field=models.CharField(choices=[('R', 'Красная'), ('Y', 'Желтая'), ('G', 'Зеленая')], default='R', max_length=5, verbose_name='Зона'),
        ),
    ]
