# Generated by Django 5.0.4 on 2024-09-29 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0072_alter_answer_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='reports.field', verbose_name='критерий'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='reports.field', verbose_name='критерий'),
        ),
        migrations.AlterField(
            model_name='rangeoption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='range_options', to='reports.field', verbose_name='критерий'),
        ),
        migrations.RemoveField(
            model_name='field',
            name='green_zone_min',
        ),
        migrations.RemoveField(
            model_name='field',
            name='yellow_zone_min',
        ),
        migrations.AddField(
            model_name='field',
            name='answer_type',
            field=models.CharField(choices=[('BL', 'Бинарный выбор (Да/Нет)'), ('LST', 'Выбор из списка'), ('NMBR', 'Числовое значение'), ('PRC', 'Процент')], default='BL', max_length=5, verbose_name='Тип ответа'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='field',
            name='bool_points',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Баллы (если бинарный выбор)'),
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
