# Generated by Django 5.0.4 on 2024-09-29 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0073_alter_option_question_alter_answer_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='attachment_name',
            field=models.CharField(blank=True, default='', max_length=750, null=True, verbose_name='Название вложения'),
        ),
        migrations.AddField(
            model_name='field',
            name='attachment_type',
            field=models.CharField(blank=True, choices=[('DC', 'Документ (прикреплённый файл)'), ('LNK', 'Ссылка'), ('OTH', 'Иной источник (без ссылки/файла)')], max_length=3, null=True, verbose_name='Цель обучения'),
        ),
    ]
