# Generated by Django 5.0.4 on 2024-09-29 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0075_alter_field_attachment_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'Показатель отчёта', 'verbose_name_plural': 'Показатели отчётов'},
        ),
        migrations.RemoveField(
            model_name='reportfile',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='reportfile',
            name='attachment',
        ),
        migrations.AddField(
            model_name='reportfile',
            name='answer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='reports.answer', verbose_name='условие'),
            preserve_default=False,
        ),
    ]
