# Generated by Django 5.0.4 on 2024-09-29 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0072_alter_section_options'),
        ('reports', '0077_answer_file'),
    ]

    operations = [
    ]
