# Generated by Django 5.0.4 on 2024-10-01 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0078_alter_field_options_answer_link_and_more'),
        ('reports', '0078_merge_0072_alter_section_options_0077_answer_file'),
    ]

    operations = [
    ]
