# Generated by Django 5.0.4 on 2024-10-09 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0080_alter_field_attachment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Название'),
        ),
    ]
