# Generated by Django 5.0.4 on 2024-11-01 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0081_alter_option_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='field',
            options={'ordering': ['number'], 'verbose_name': 'Показатель', 'verbose_name_plural': 'Показатели'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'Критерий', 'verbose_name_plural': 'Критерии'},
        ),
        migrations.AlterField(
            model_name='field',
            name='name',
            field=models.CharField(max_length=750, verbose_name='Название показателя'),
        ),
        migrations.AlterField(
            model_name='field',
            name='number',
            field=models.CharField(max_length=500, verbose_name='Номер показатель'),
        ),
        migrations.AlterField(
            model_name='section',
            name='fields',
            field=models.ManyToManyField(blank=True, related_name='sections', to='reports.field', verbose_name='Показатели'),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Название критерия'),
        ),
        migrations.AlterField(
            model_name='section',
            name='number',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Номер критерия'),
        ),
    ]
