# Generated by Django 5.0.4 on 2024-11-11 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0082_alter_field_options_alter_section_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolreport',
            name='status',
            field=models.CharField(choices=[('C', 'Заполнение'), ('A', 'На согласовании в ТУ/ДО'), ('B', 'Отправлено в МинОбр'), ('D', 'Принят')], default='C', max_length=1, verbose_name='Статус'),
        ),
    ]
