# Generated by Django 5.0.4 on 2024-11-11 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0083_alter_schoolreport_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(blank=True, max_length=1500, null=True, verbose_name='Ссылка')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='reports.answer', verbose_name='ответ')),
                ('s_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='reports.schoolreport', verbose_name='отчёт')),
            ],
            options={
                'verbose_name': 'Ссылка',
                'verbose_name_plural': 'Ссылки',
            },
        ),
    ]
