# Generated by Django 5.0.4 on 2025-02-02 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0084_reportlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionSreport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Колво баллов')),
                ('zone', models.CharField(choices=[('R', 'Красная'), ('Y', 'Желтая'), ('G', 'Зеленая')], default='R', max_length=5, verbose_name='Зона')),
                ('s_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='reports.schoolreport', verbose_name='отчёт')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s_reports', to='reports.section', verbose_name='раздел')),
            ],
            options={
                'verbose_name': 'Раздел отчёта школы',
                'verbose_name_plural': 'Разделы отчётов школ',
            },
        ),
    ]
