# Generated by Django 5.0.4 on 2025-02-05 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0085_sectionsreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionsreport',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='s_reports', to='reports.section', verbose_name='раздел'),
        ),
    ]
