# Generated by Django 5.0.4 on 2025-03-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0087_alter_option_options_answer_selected_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolreport',
            name='deletion_date',
            field=models.DateTimeField(blank=True, help_text='Дата, когда отчёт будет фактически удален', null=True, verbose_name='Дата удаления'),
        ),
        migrations.AddField(
            model_name='schoolreport',
            name='is_marked_for_deletion',
            field=models.BooleanField(default=False, help_text='Если отмечено, отчёт будет удален после истечения срока', verbose_name='Отмечен на удаление'),
        ),
    ]
