# Generated by Django 5.0.4 on 2025-03-09 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0088_schoolreport_deletion_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True, verbose_name='Год')),
                ('status', models.CharField(choices=[('forming', 'Формирование отчётов'), ('updating', 'Обновление школ ТУ/ДО'), ('filling', 'Заполнение и проверка отчётов'), ('completed', 'Завершено')], default='forming', help_text="\n        'Формирование отчётов' - отчёты этого года школ не формируются;\n        'Обновление школ ТУ/ДО' - даёт возможность редактировать школы пользователям с ролью «ТУ/ДО»;\n        'Заполнение и проверка отчётов' - активная фаза работы с отчетами;\n        'Завершено' - закрыт доступ к редактированию шаблонов и отчётов школ этого года\n        ", max_length=20, verbose_name='Статус')),
                ('is_current', models.BooleanField(default=False, help_text='Отметьте, если это текущий рабочий год', verbose_name='Текущий год?')),
            ],
            options={
                'verbose_name': 'Год',
                'verbose_name_plural': 'Годы',
                'ordering': ['-year'],
            },
        ),
    ]
