# Generated by Django 5.0.4 on 2025-03-09 11:45

import django.db.models.deletion
from django.db import migrations, models


def update_year_field(apps, schema_editor):
    """
    Исправляет ссылки между полями year и year_ref в модели Report
    """
    Report = apps.get_model('reports', 'Report')
    Year = apps.get_model('reports', 'Year')
    
    # Создаем словарь для быстрого поиска объектов Year по значению year
    year_dict = {y.year: y for y in Year.objects.all()}
    
    # Обновляем все отчеты, связывая year_ref с объектом Year,
    # соответствующим значению поля year
    for report in Report.objects.all():
        year_value = report.year
        year_obj = year_dict.get(year_value)
        
        if year_obj and report.year_ref_id != year_obj.id:
            report.year_ref = year_obj
            report.save(update_fields=['year_ref'])


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0091_report_year_ref_alter_report_year'),
    ]

    operations = [
        # Запускаем функцию для обновления связей
        migrations.RunPython(update_year_field, migrations.RunPython.noop),
    ]
