# Generated by Django 5.0.4 on 2025-03-09 11:46

import django.db.models.deletion
from django.db import migrations, models


def copy_year_ref_to_year(apps, schema_editor):
    """
    Копирует внешние ключи из year_ref в year перед удалением year_ref
    """
    # Используем прямой SQL-запрос для обновления поля year
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        # Сначала добавляем колонку year_id
        cursor.execute("ALTER TABLE reports_report ADD COLUMN year_id INTEGER REFERENCES reports_year(id)")
        
        # Копируем значения из year_ref_id в year_id
        cursor.execute("UPDATE reports_report SET year_id = year_ref_id WHERE year_ref_id IS NOT NULL")
        
        # Удаляем колонку year (числовое поле)
        cursor.execute("ALTER TABLE reports_report DROP COLUMN year")
        
        # Удаляем колонку year_ref_id
        cursor.execute("ALTER TABLE reports_report DROP COLUMN year_ref_id")


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0092_restore_report_structure'),
    ]

    operations = [
        # Выполняем SQL-запросы для изменения структуры таблицы
        migrations.RunPython(copy_year_ref_to_year, migrations.RunPython.noop),
    ]
