# Generated by Django 5.0.4 on 2025-03-09 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0093_remove_report_year_ref_alter_report_year'),
    ]

    operations = [
        # Пустая миграция, так как поле year_id уже существует в базе данных
        # Модель Report уже обновлена в коде
    ]
