# Generated by Django 5.0.4 on 2025-04-02 11:14

from django.db import migrations


def conditional_operations(apps, schema_editor):
    """
    Проверяет наличие колонки year_ref_id перед её удалением
    """
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        # Проверяем существует ли колонка year_ref_id в таблице reports_report
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='reports_report' AND column_name='year_ref_id'
        """)
        
        # Если колонка существует, удаляем её
        if cursor.fetchone():
            cursor.execute("ALTER TABLE reports_report DROP COLUMN year_ref_id")


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0095_remove_report_year_ref_field_green_zone_min_and_more'),
    ]

    operations = [
        # Выполняем условное удаление колонки
        migrations.RunPython(conditional_operations, migrations.RunPython.noop),
    ]
