# Generated by Django 5.0.4 on 2025-04-14 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0095_remove_report_year_ref_field_green_zone_min_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='checked_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата проверки'),
        ),
        migrations.AddField(
            model_name='answer',
            name='checked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_answers', to=settings.AUTH_USER_MODEL, verbose_name='Проверил'),
        ),
        migrations.AddField(
            model_name='answer',
            name='is_checked',
            field=models.BooleanField(default=False, verbose_name='Проверено'),
        ),
    ]
