# Generated by Django 5.0.4 on 2025-04-16 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_schoolreport_is_outdated'),
        ('reports', '0096_auto_20250414_1217'),
    ]

    operations = [
    ]
