# Generated by Django 5.0.4 on 2025-04-18 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0096_conditional_remove_year_ref_id'),
        ('reports', '0097_merge_20250416_1235'),
    ]

    operations = [
    ]
