# Generated by Django 5.0.4 on 2025-05-23 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0098_merge_20250418_1115'),
        ('reports', '0098_merge_20250418_1241'),
    ]

    operations = [
    ]
