# Generated by Django 5.0.4 on 2025-10-16 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0099_merge_20250523_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='year',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fields', to='reports.year', verbose_name='Год'),
        ),
    ]
