# Generated by Django 5.0.4 on 2025-10-16 08:44

import django.db.models.deletion
from django.db import migrations, models


def migrate_year_to_years(apps, schema_editor):
    """
    Переносит данные из ForeignKey year в ManyToMany years
    """
    Field = apps.get_model('reports', 'Field')
    
    for field in Field.objects.all():
        # Получаем старое значение year_id напрямую из БД
        if hasattr(field, 'year_id') and field.year_id:
            # Добавляем старый год в новое поле years
            field.years.add(field.year_id)
        elif not field.years.exists():
            # Если нет года, добавляем 2024 (id=1)
            field.years.add(1)


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0100_alter_schoolreport_options_remove_report_year_ref_and_more'),
    ]

    operations = [
        # Сначала добавляем новое ManyToMany поле
        migrations.AddField(
            model_name='field',
            name='years',
            field=models.ManyToManyField(blank=True, related_name='fields', to='reports.year', verbose_name='Годы'),
        ),
        # Переносим данные из старого поля в новое
        migrations.RunPython(migrate_year_to_years, migrations.RunPython.noop),
        # Удаляем старое поле year
        migrations.RemoveField(
            model_name='field',
            name='year',
        ),
    ]
