# Generated by Django 5.0.4 on 2025-10-16 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0101_change_field_year_to_manytomany'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolreport',
            options={'verbose_name': 'Отчёт школы', 'verbose_name_plural': 'Отчёты школ'},
        ),
        migrations.RemoveField(
            model_name='report',
            name='year_ref',
        ),
        migrations.AlterField(
            model_name='report',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='reports.year', verbose_name='Год'),
        ),
    ]
