# Generated by Django 5.0.4 on 2024-05-06 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Полное наименование')),
                ('short_name', models.CharField(max_length=125, verbose_name='Сокращенное наименование')),
            ],
            options={
                'verbose_name': 'Тип учебного учреждения',
                'verbose_name_plural': 'Типы учебных учреждений',
            },
        ),
        migrations.CreateModel(
            name='TerAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('representative', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ter_admin', to=settings.AUTH_USER_MODEL, verbose_name='Представитель ТУ/ДО')),
            ],
            options={
                'verbose_name': 'ТУ/ДО',
                'verbose_name_plural': 'ТУ/ДО',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Полное наименование')),
                ('short_name', models.CharField(max_length=125, verbose_name='Сокращенное наименование')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Официальный email')),
                ('city', models.CharField(max_length=250, verbose_name='Населённый пункт')),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='Номер школы')),
                ('principal', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='school', to=settings.AUTH_USER_MODEL, verbose_name='Директор')),
                ('school_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='schools.schooltype', verbose_name='Тип школы')),
                ('ter_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='schools.teradmin', verbose_name='ТУ/ДО')),
            ],
            options={
                'verbose_name': 'Школа',
                'verbose_name_plural': 'Школы',
            },
        ),
    ]
