# Generated by Django 5.0.4 on 2024-05-06 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='principal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='school', to=settings.AUTH_USER_MODEL, verbose_name='Директор'),
        ),
        migrations.AlterField(
            model_name='teradmin',
            name='representative',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ter_admin', to=settings.AUTH_USER_MODEL, verbose_name='Представитель ТУ/ДО'),
        ),
    ]
