# Generated by Django 5.0.4 on 2024-05-06 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_alter_school_principal_alter_teradmin_representative'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='inn',
            field=models.CharField(default=123124, max_length=20, unique=True, verbose_name='ИНН'),
            preserve_default=False,
        ),
    ]
