# Generated by Django 5.0.4 on 2024-05-06 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_alter_school_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='city',
            field=models.CharField(max_length=250, null=True, verbose_name='Населённый пункт'),
        ),
        migrations.AlterField(
            model_name='school',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Официальный email'),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=500, null=True, verbose_name='Полное наименование'),
        ),
        migrations.AlterField(
            model_name='school',
            name='short_name',
            field=models.CharField(max_length=125, null=True, verbose_name='Сокращенное наименование'),
        ),
    ]
