# Generated by Django 5.0.4 on 2024-05-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_alter_school_city_alter_school_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Код регистрации'),
        ),
    ]
