# Generated by Django 5.0.4 on 2024-06-15 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0007_alter_school_principal_alter_teradmin_representative'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolCloster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Кластер',
                'verbose_name_plural': 'Кластеры',
            },
        ),
        migrations.RemoveField(
            model_name='school',
            name='code',
        ),
        migrations.AlterField(
            model_name='school',
            name='school_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='schools.schooltype', verbose_name='Тип школы'),
        ),
        migrations.AddField(
            model_name='school',
            name='сloster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='schools.schoolcloster', verbose_name='Кластер'),
        ),
    ]
