# Generated by Django 5.0.4 on 2024-06-17 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0008_schoolcloster_remove_school_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='сloster',
            new_name='closter',
        ),
    ]
