# Generated by Django 5.0.4 on 2024-06-22 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0010_alter_school_school_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='inn',
        ),
        migrations.AddField(
            model_name='school',
            name='ais_id',
            field=models.IntegerField(null=True, unique=True, verbose_name='ID в АИС "Кадры в образовании"'),
        ),
    ]
