# Generated by Django 5.0.4 on 2024-10-09 10:01

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0013_questioncategory_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=tinymce.models.HTMLField(blank=True, default=None, null=True, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=tinymce.models.HTMLField(verbose_name='Вопрос'),
        ),
    ]
