# Generated by Django 5.0.4 on 2024-10-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0014_alter_question_answer_alter_question_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_visible',
            field=models.BooleanField(default=False, verbose_name='Отображать на сайте'),
        ),
    ]
