# Generated by Django 5.0.4 on 2024-10-13 17:33

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0015_question_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='short_question',
            field=models.CharField(default=1, max_length=250, verbose_name='Вопрос'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Пояснение'),
        ),
    ]
