# Generated by Django 5.0.4 on 2024-10-13 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0016_question_short_question_alter_question_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='display_on_site',
        ),
    ]
