# Generated by Django 5.0.4 on 2024-10-13 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0017_remove_question_display_on_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='schools.questioncategory', verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
