# Generated by Django 5.0.4 on 2024-10-25 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0018_alter_question_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=1000, null=True, verbose_name='Полное наименование'),
        ),
        migrations.AlterField(
            model_name='school',
            name='short_name',
            field=models.CharField(max_length=500, null=True, verbose_name='Сокращенное наименование'),
        ),
    ]
