# Generated by Django 5.0.4 on 2024-12-02 12:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0021_remove_teradmin_representative_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='number',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Номер школы'),
        ),
        migrations.AlterField(
            model_name='teradmin',
            name='representatives',
            field=models.ManyToManyField(blank=True, related_name='ter_admin', to=settings.AUTH_USER_MODEL, verbose_name='Представитель ТУ/ДО'),
        ),
    ]
