# Generated by Django 5.0.4 on 2025-02-02 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0022_alter_school_number_alter_teradmin_representatives'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер/название школы'),
        ),
    ]
