# Generated by Django 5.0.4 on 2025-03-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0023_alter_school_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='При активации этого статуса школа и её отчеты скрываются из пользовательского интерфейса, а аккаунт школы деактивируется.', verbose_name='Архивная школа'),
        ),
    ]
